### ISSUE TITLE
Replace hardcoded min value in lw_solver example

### ISSUE THREAD

**Issue by tcmetzger** [earth-system-radiation/pyRTE-RRTMGP#32]
In the low_noscat usage example, we currently use a hardcoded value (copied from Fortran): 

`rfmip["pres_level"][:, min_index] = 1.0051835744630002`

This should be replaced, either by a more "numpy way" of doing things or at least better documenting where this value comes from.

**Comment by sehnem** [comment]
@tcmetzger this have been solved with PR that was merged.
